import Foundation

@main
struct RemoteControlTests {
    @MainActor static func main() async throws {
        precondition(RemoteMode.available(context: "browser", external: false, supportsRemote: true) == [.context, .dpad, .touchpad, .keyboard])
        precondition(RemoteMode.available(context: "player", external: false, supportsRemote: true) == [.context, .dpad, .touchpad])
        precondition(RemoteMode.available(context: "browser", external: true, supportsRemote: true) == [.context, .dpad])
        precondition(RemoteMode.available(context: "player", external: true, supportsRemote: false) == [.context])
        precondition(RemoteMode.supportsRemote(externalProtocol: nil) && RemoteMode.supportsRemote(externalProtocol: "roku"))
        precondition(!RemoteMode.supportsRemote(externalProtocol: "google_cast") && !RemoteMode.supportsVolume(externalProtocol: "dlna"))
        precondition(RemoteMode.canSeek(context: "browser", externalProtocol: nil, duration: 1000, isLive: true, isSeekable: false))
        precondition(!RemoteMode.canSeek(context: "player", externalProtocol: nil, duration: 1000, isLive: true, isSeekable: true))
        precondition(!RemoteMode.canSeek(context: "player", externalProtocol: "roku", duration: 1000, isLive: false, isSeekable: true))
        precondition(RemoteMode.canSeek(context: "player", externalProtocol: "google_cast", duration: 1000, isLive: false, isSeekable: true))
        precondition(!RemoteMode.canSeek(context: "player", externalProtocol: nil, duration: 1000, isLive: false, isSeekable: true, isImage: true))
        precondition(!RemoteMode.canSeek(context: "idle", externalProtocol: nil, duration: 1000, isLive: false, isSeekable: true))
        precondition(RemoteMode.time(3_661_000) == "1:01:01" && RemoteMode.time(-1) == "00:00")
        precondition(RemoteSeekBehavior.mode(heldFor: 0.39) == .relative)
        precondition(RemoteSeekBehavior.mode(heldFor: 0.4) == .absolute)
        let relative = RemoteSeekBehavior.target(currentMs: 3_000_000, durationMs: 3_600_000, width: 300, fingerX: 150, dragX: 300, mode: .relative)
        precondition(relative == 3_360_000)
        precondition(RemoteSeekBehavior.target(currentMs: 300_000, durationMs: 600_000, width: 100, fingerX: 0, dragX: 100, mode: .relative) == 420_000)
        precondition(RemoteSeekBehavior.target(currentMs: 3_000_000, durationMs: 10_800_000, width: 100, fingerX: 0, dragX: 100, mode: .relative) == 3_600_000)
        precondition(RemoteSeekBehavior.target(currentMs: 100_000, durationMs: 600_000, width: 100, fingerX: 0, dragX: -100, mode: .relative) == 0)
        precondition(RemoteSeekBehavior.target(currentMs: 3_000_000, durationMs: 3_600_000, width: 300, fingerX: 150, dragX: 0, mode: .absolute) == 1_800_000)
        precondition(RemoteSeekBehavior.target(currentMs: 3_000_000, durationMs: 3_600_000, width: 300, fingerX: 0, dragX: 0, mode: .absolute) == 0)
        precondition(RemoteSeekBehavior.target(currentMs: 3_000_000, durationMs: 3_600_000, width: 300, fingerX: 300, dragX: 0, mode: .absolute) == 3_600_000)
        precondition(RemoteSeekBehavior.signedOffset(targetMs: 3_360_000, currentMs: 3_000_000) == "+06:00")
        precondition(RemoteSeekBehavior.signedOffset(targetMs: 1_800_000, currentMs: 3_000_000) == "-20:00")
        precondition(MousePacket.pack(event: "zoom", dx: 1.5, dy: 0).first == 5)
        precondition(MousePacket.pack(event: "reset", dx: 0, dy: 0).first == 6)
        precondition(MousePacket.pack(event: "rotate", dx: 90, dy: 0).first == 7)
        precondition(MousePacket.pack(event: "transform_anchor", dx: -1, dy: -1).first == 8)
        let coordinator = ConnectionCoordinator()
        coordinator.handle(#"{"type":"tracks","audio":[{"id":7,"name":"English","selected":true}],"subtitle":[{"id":"none","name":"Off","selected":true}]}"#)
        coordinator.handle(#"{"type":"player_settings","speed":1.5,"scaling":"Zoom","isLive":true,"isSeekable":false,"speedAvailable":false}"#)
        try await Task.sleep(nanoseconds: 50_000_000)
        precondition(coordinator.audioTracks.first?.id == "7")
        precondition(coordinator.subtitleTracks.first?.id == "none")
        precondition(coordinator.playerIsLive && !coordinator.playerIsSeekable && !coordinator.speedAvailable)
        precondition(coordinator.playerSpeed == 1.5 && coordinator.playerScaling == "Zoom")
        coordinator.handle(#"{"type":"context","active":"idle"}"#)
        try await Task.sleep(nanoseconds: 50_000_000)
        precondition(coordinator.audioTracks.isEmpty && !coordinator.playerIsLive && coordinator.playerIsSeekable)
        let message = WireProtocol.browserControlCommand("refresh")
        let json = try JSONSerialization.jsonObject(with: Data(message.utf8)) as! [String: Any]
        precondition(json["action"] as? String == "browser_control")
        precondition((json["payload"] as? [String: Any])?["action"] as? String == "refresh")
        print("PASS: remote modes, timeline capabilities, track IDs, settings reset and browser commands")
    }
}
