package com.playbridge.player.player

internal object RendererProtocol {
    const val KEY_SESSION_ID = "renderer_session_id"
    const val KEY_RENDERER = "renderer"
    const val KEY_URL = "url"
    const val KEY_TITLE = "title"
    const val KEY_CONTENT_TYPE = "content_type"
    const val KEY_HEADERS = "headers"
    const val KEY_PAYLOAD_JSON = "payload_json"
    const val KEY_EVENT = "event"
    const val KEY_ERROR = "error"
    const val KEY_STATE = "state"
    const val KEY_POSITION_MS = "position_ms"
    const val KEY_DURATION_MS = "duration_ms"
    const val KEY_VIDEO_WIDTH = "video_width"
    const val KEY_VIDEO_HEIGHT = "video_height"
    const val KEY_VIDEO_FPS = "video_fps"
    const val KEY_VIDEO_TRACKS = "video_tracks"
    const val KEY_AUDIO_TRACKS = "audio_tracks"
    const val KEY_SUBTITLE_TRACKS = "subtitle_tracks"
    const val KEY_TRACK_ID = "track_id"
    const val KEY_TRACK_LABEL = "track_label"
    const val KEY_TRACK_LANGUAGE = "track_language"
    const val KEY_TRACK_SELECTED = "track_selected"
    const val KEY_CUE_GROUP = "cue_group"
    const val KEY_SUBTITLE_URI = "subtitle_uri"
    const val KEY_INITIAL_SUBTITLE_URI = "initial_subtitle_uri"
    const val KEY_INITIAL_SUBTITLE_LABEL = "initial_subtitle_label"
    const val KEY_SUCCESS = "success"

    const val EVENT_READY = "ready"
    const val EVENT_FIRST_FRAME = "first_frame"
    const val EVENT_STATE = "state"
    const val EVENT_ENDED = "ended"
    const val EVENT_VIDEO_SIZE = "video_size"
    const val EVENT_TRACKS = "tracks"
    const val EVENT_CUES = "cues"
    const val EVENT_EXTERNAL_SUBTITLE_RESULT = "external_subtitle_result"
    const val EVENT_STOPPED = "stopped"
    const val EVENT_ERROR = "error"
}
