// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.AuthResponse in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class AuthResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val success: Boolean = false,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val token: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AuthResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AuthResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (success != other.success) return false
    if (token != other.token) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + success.hashCode()
      result = result * 37 + (token?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    result += """success=$success"""
    if (token != null) result += """token=${sanitize(token)}"""
    return result.joinToString(prefix = "AuthResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    success: Boolean = this.success,
    token: String? = this.token,
    unknownFields: ByteString = this.unknownFields,
  ): AuthResponse = AuthResponse(type, success, token, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AuthResponse> = object : ProtoAdapter<AuthResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      AuthResponse::class, 
      "type.googleapis.com/playbridge.AuthResponse", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: AuthResponse): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        if (value.success != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.success)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.token)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AuthResponse) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.token)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AuthResponse) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.token)
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): AuthResponse {
        var type: String = ""
        var success: Boolean = false
        var token: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> success = ProtoAdapter.BOOL.decode(reader)
            3 -> token = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AuthResponse(
          type = type,
          success = success,
          token = token,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AuthResponse): AuthResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
