// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.BrowserPayload in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class BrowserPayload(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val url: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "browserMode",
    schemaIndex = 1,
  )
  public val browser_mode: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    jsonName = "desktopMode",
    schemaIndex = 2,
  )
  public val desktop_mode: Boolean? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<BrowserPayload, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BrowserPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (url != other.url) return false
    if (browser_mode != other.browser_mode) return false
    if (desktop_mode != other.desktop_mode) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + (browser_mode?.hashCode() ?: 0)
      result = result * 37 + (desktop_mode?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """url=${sanitize(url)}"""
    if (browser_mode != null) result += """browser_mode=${sanitize(browser_mode)}"""
    if (desktop_mode != null) result += """desktop_mode=$desktop_mode"""
    return result.joinToString(prefix = "BrowserPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(
    url: String = this.url,
    browser_mode: String? = this.browser_mode,
    desktop_mode: Boolean? = this.desktop_mode,
    unknownFields: ByteString = this.unknownFields,
  ): BrowserPayload = BrowserPayload(url, browser_mode, desktop_mode, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BrowserPayload> = object : ProtoAdapter<BrowserPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      BrowserPayload::class, 
      "type.googleapis.com/playbridge.BrowserPayload", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: BrowserPayload): Int {
        var size = value.unknownFields.size
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.browser_mode)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.desktop_mode)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BrowserPayload) {
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.browser_mode)
        ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.desktop_mode)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BrowserPayload) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.desktop_mode)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.browser_mode)
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        }
      }

      override fun decode(reader: ProtoReader): BrowserPayload {
        var url: String = ""
        var browser_mode: String? = null
        var desktop_mode: Boolean? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> url = ProtoAdapter.STRING.decode(reader)
            2 -> browser_mode = ProtoAdapter.STRING.decode(reader)
            3 -> desktop_mode = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BrowserPayload(
          url = url,
          browser_mode = browser_mode,
          desktop_mode = desktop_mode,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BrowserPayload): BrowserPayload = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
