// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.BrowserControlPayload in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class BrowserControlPayload(
  /**
   * refresh | toggle_ublock
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val action: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<BrowserControlPayload, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BrowserControlPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (action != other.action) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + action.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """action=${sanitize(action)}"""
    return result.joinToString(prefix = "BrowserControlPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(action: String = this.action, unknownFields: ByteString = this.unknownFields):
      BrowserControlPayload = BrowserControlPayload(action, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BrowserControlPayload> = object :
        ProtoAdapter<BrowserControlPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      BrowserControlPayload::class, 
      "type.googleapis.com/playbridge.BrowserControlPayload", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: BrowserControlPayload): Int {
        var size = value.unknownFields.size
        if (value.action != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.action)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BrowserControlPayload) {
        if (value.action != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.action)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BrowserControlPayload) {
        writer.writeBytes(value.unknownFields)
        if (value.action != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.action)
        }
      }

      override fun decode(reader: ProtoReader): BrowserControlPayload {
        var action: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> action = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BrowserControlPayload(
          action = action,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BrowserControlPayload): BrowserControlPayload = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
