// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.ControlPayload in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ControlPayload(
  /**
   * pause | play | seek | stop
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val command: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ControlPayload, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ControlPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (command != other.command) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + command.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """command=${sanitize(command)}"""
    return result.joinToString(prefix = "ControlPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(command: String = this.command, unknownFields: ByteString = this.unknownFields):
      ControlPayload = ControlPayload(command, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ControlPayload> = object : ProtoAdapter<ControlPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      ControlPayload::class, 
      "type.googleapis.com/playbridge.ControlPayload", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: ControlPayload): Int {
        var size = value.unknownFields.size
        if (value.command != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.command)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ControlPayload) {
        if (value.command != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.command)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ControlPayload) {
        writer.writeBytes(value.unknownFields)
        if (value.command != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.command)
        }
      }

      override fun decode(reader: ProtoReader): ControlPayload {
        var command: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> command = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ControlPayload(
          command = command,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ControlPayload): ControlPayload = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
