// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.MessageEnvelope in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ==================== Envelope ====================
 * Top-level WebSocket frame. Consumers switch on `type`, then `action`.
 */
public class MessageEnvelope(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val action: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val state: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    schemaIndex = 3,
  )
  public val position: Long? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    schemaIndex = 4,
  )
  public val duration: Long? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 5,
  )
  public val title: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MessageEnvelope, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MessageEnvelope) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (action != other.action) return false
    if (state != other.state) return false
    if (position != other.position) return false
    if (duration != other.duration) return false
    if (title != other.title) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (state?.hashCode() ?: 0)
      result = result * 37 + (position?.hashCode() ?: 0)
      result = result * 37 + (duration?.hashCode() ?: 0)
      result = result * 37 + (title?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    if (action != null) result += """action=${sanitize(action)}"""
    if (state != null) result += """state=${sanitize(state)}"""
    if (position != null) result += """position=$position"""
    if (duration != null) result += """duration=$duration"""
    if (title != null) result += """title=${sanitize(title)}"""
    return result.joinToString(prefix = "MessageEnvelope{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    action: String? = this.action,
    state: String? = this.state,
    position: Long? = this.position,
    duration: Long? = this.duration,
    title: String? = this.title,
    unknownFields: ByteString = this.unknownFields,
  ): MessageEnvelope = MessageEnvelope(type, action, state, position, duration, title,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MessageEnvelope> = object : ProtoAdapter<MessageEnvelope>(
      FieldEncoding.LENGTH_DELIMITED, 
      MessageEnvelope::class, 
      "type.googleapis.com/playbridge.MessageEnvelope", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: MessageEnvelope): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.action)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.state)
        size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.position)
        size += ProtoAdapter.INT64.encodedSizeWithTag(5, value.duration)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.title)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MessageEnvelope) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.state)
        ProtoAdapter.INT64.encodeWithTag(writer, 4, value.position)
        ProtoAdapter.INT64.encodeWithTag(writer, 5, value.duration)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.title)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MessageEnvelope) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.title)
        ProtoAdapter.INT64.encodeWithTag(writer, 5, value.duration)
        ProtoAdapter.INT64.encodeWithTag(writer, 4, value.position)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.state)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.action)
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): MessageEnvelope {
        var type: String = ""
        var action: String? = null
        var state: String? = null
        var position: Long? = null
        var duration: Long? = null
        var title: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> action = ProtoAdapter.STRING.decode(reader)
            3 -> state = ProtoAdapter.STRING.decode(reader)
            4 -> position = ProtoAdapter.INT64.decode(reader)
            5 -> duration = ProtoAdapter.INT64.decode(reader)
            6 -> title = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MessageEnvelope(
          type = type,
          action = action,
          state = state,
          position = position,
          duration = duration,
          title = title,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MessageEnvelope): MessageEnvelope = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
