// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.PairingApprovedMessage in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * TV → Phone: user tapped Allow.
 */
public class PairingApprovedMessage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val token: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PairingApprovedMessage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PairingApprovedMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (token != other.token) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + token.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    result += """token=${sanitize(token)}"""
    return result.joinToString(prefix = "PairingApprovedMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    token: String = this.token,
    unknownFields: ByteString = this.unknownFields,
  ): PairingApprovedMessage = PairingApprovedMessage(type, token, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PairingApprovedMessage> = object :
        ProtoAdapter<PairingApprovedMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      PairingApprovedMessage::class, 
      "type.googleapis.com/playbridge.PairingApprovedMessage", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: PairingApprovedMessage): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        if (value.token != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.token)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PairingApprovedMessage) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        if (value.token != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.token)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PairingApprovedMessage) {
        writer.writeBytes(value.unknownFields)
        if (value.token != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.token)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): PairingApprovedMessage {
        var type: String = ""
        var token: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> token = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PairingApprovedMessage(
          type = type,
          token = token,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PairingApprovedMessage): PairingApprovedMessage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
