// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.PlayPayload in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * ==================== Command Payloads (Phone → TV) ====================
 */
public class PlayPayload(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val url: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val title: String? = null,
  headers: Map<String, String> = emptyMap(),
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "contentType",
    schemaIndex = 3,
  )
  public val content_type: String? = null,
  subtitles: List<String> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "detectedBy",
    schemaIndex = 5,
  )
  public val detected_by: String? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "playerMode",
    schemaIndex = 6,
  )
  public val player_mode: String? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "preferredAudioLanguage",
    schemaIndex = 7,
  )
  public val preferred_audio_language: String? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "preferredSubtitleLanguage",
    schemaIndex = 8,
  )
  public val preferred_subtitle_language: String? = null,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "defaultVideoQuality",
    schemaIndex = 9,
  )
  public val default_video_quality: String? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    jsonName = "maxBitrateCapMbps",
    schemaIndex = 10,
  )
  public val max_bitrate_cap_mbps: Double? = null,
  @field:WireField(
    tag = 12,
    adapter = "playbridge.VisualMetadata#ADAPTER",
    jsonName = "visualMetadata",
    schemaIndex = 11,
  )
  public val visual_metadata: VisualMetadata? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PlayPayload, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val headers: Map<String, String> = immutableCopyOf("headers", headers)

  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val subtitles: List<String> = immutableCopyOf("subtitles", subtitles)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PlayPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (url != other.url) return false
    if (title != other.title) return false
    if (headers != other.headers) return false
    if (content_type != other.content_type) return false
    if (subtitles != other.subtitles) return false
    if (detected_by != other.detected_by) return false
    if (player_mode != other.player_mode) return false
    if (preferred_audio_language != other.preferred_audio_language) return false
    if (preferred_subtitle_language != other.preferred_subtitle_language) return false
    if (default_video_quality != other.default_video_quality) return false
    if (max_bitrate_cap_mbps != other.max_bitrate_cap_mbps) return false
    if (visual_metadata != other.visual_metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + (title?.hashCode() ?: 0)
      result = result * 37 + headers.hashCode()
      result = result * 37 + (content_type?.hashCode() ?: 0)
      result = result * 37 + subtitles.hashCode()
      result = result * 37 + (detected_by?.hashCode() ?: 0)
      result = result * 37 + (player_mode?.hashCode() ?: 0)
      result = result * 37 + (preferred_audio_language?.hashCode() ?: 0)
      result = result * 37 + (preferred_subtitle_language?.hashCode() ?: 0)
      result = result * 37 + (default_video_quality?.hashCode() ?: 0)
      result = result * 37 + (max_bitrate_cap_mbps?.hashCode() ?: 0)
      result = result * 37 + (visual_metadata?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """url=${sanitize(url)}"""
    if (title != null) result += """title=${sanitize(title)}"""
    if (headers.isNotEmpty()) result += """headers=$headers"""
    if (content_type != null) result += """content_type=${sanitize(content_type)}"""
    if (subtitles.isNotEmpty()) result += """subtitles=${sanitize(subtitles)}"""
    if (detected_by != null) result += """detected_by=${sanitize(detected_by)}"""
    if (player_mode != null) result += """player_mode=${sanitize(player_mode)}"""
    if (preferred_audio_language != null) result +=
        """preferred_audio_language=${sanitize(preferred_audio_language)}"""
    if (preferred_subtitle_language != null) result +=
        """preferred_subtitle_language=${sanitize(preferred_subtitle_language)}"""
    if (default_video_quality != null) result +=
        """default_video_quality=${sanitize(default_video_quality)}"""
    if (max_bitrate_cap_mbps != null) result += """max_bitrate_cap_mbps=$max_bitrate_cap_mbps"""
    if (visual_metadata != null) result += """visual_metadata=$visual_metadata"""
    return result.joinToString(prefix = "PlayPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(
    url: String = this.url,
    title: String? = this.title,
    headers: Map<String, String> = this.headers,
    content_type: String? = this.content_type,
    subtitles: List<String> = this.subtitles,
    detected_by: String? = this.detected_by,
    player_mode: String? = this.player_mode,
    preferred_audio_language: String? = this.preferred_audio_language,
    preferred_subtitle_language: String? = this.preferred_subtitle_language,
    default_video_quality: String? = this.default_video_quality,
    max_bitrate_cap_mbps: Double? = this.max_bitrate_cap_mbps,
    visual_metadata: VisualMetadata? = this.visual_metadata,
    unknownFields: ByteString = this.unknownFields,
  ): PlayPayload = PlayPayload(url, title, headers, content_type, subtitles, detected_by,
      player_mode, preferred_audio_language, preferred_subtitle_language, default_video_quality,
      max_bitrate_cap_mbps, visual_metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PlayPayload> = object : ProtoAdapter<PlayPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      PlayPayload::class, 
      "type.googleapis.com/playbridge.PlayPayload", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      private val headersAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: PlayPayload): Int {
        var size = value.unknownFields.size
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.title)
        size += headersAdapter.encodedSizeWithTag(3, value.headers)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.content_type)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(5, value.subtitles)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.detected_by)
        size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.player_mode)
        size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.preferred_audio_language)
        size += ProtoAdapter.STRING.encodedSizeWithTag(9, value.preferred_subtitle_language)
        size += ProtoAdapter.STRING.encodedSizeWithTag(10, value.default_video_quality)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(11, value.max_bitrate_cap_mbps)
        size += VisualMetadata.ADAPTER.encodedSizeWithTag(12, value.visual_metadata)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PlayPayload) {
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.title)
        headersAdapter.encodeWithTag(writer, 3, value.headers)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content_type)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.subtitles)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.detected_by)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.player_mode)
        ProtoAdapter.STRING.encodeWithTag(writer, 8, value.preferred_audio_language)
        ProtoAdapter.STRING.encodeWithTag(writer, 9, value.preferred_subtitle_language)
        ProtoAdapter.STRING.encodeWithTag(writer, 10, value.default_video_quality)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 11, value.max_bitrate_cap_mbps)
        VisualMetadata.ADAPTER.encodeWithTag(writer, 12, value.visual_metadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PlayPayload) {
        writer.writeBytes(value.unknownFields)
        VisualMetadata.ADAPTER.encodeWithTag(writer, 12, value.visual_metadata)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 11, value.max_bitrate_cap_mbps)
        ProtoAdapter.STRING.encodeWithTag(writer, 10, value.default_video_quality)
        ProtoAdapter.STRING.encodeWithTag(writer, 9, value.preferred_subtitle_language)
        ProtoAdapter.STRING.encodeWithTag(writer, 8, value.preferred_audio_language)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.player_mode)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.detected_by)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.subtitles)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content_type)
        headersAdapter.encodeWithTag(writer, 3, value.headers)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.title)
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        }
      }

      override fun decode(reader: ProtoReader): PlayPayload {
        var url: String = ""
        var title: String? = null
        val headers = mutableMapOf<String, String>()
        var content_type: String? = null
        val subtitles = mutableListOf<String>()
        var detected_by: String? = null
        var player_mode: String? = null
        var preferred_audio_language: String? = null
        var preferred_subtitle_language: String? = null
        var default_video_quality: String? = null
        var max_bitrate_cap_mbps: Double? = null
        var visual_metadata: VisualMetadata? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> url = ProtoAdapter.STRING.decode(reader)
            2 -> title = ProtoAdapter.STRING.decode(reader)
            3 -> headers.putAll(headersAdapter.decode(reader))
            4 -> content_type = ProtoAdapter.STRING.decode(reader)
            5 -> subtitles.add(ProtoAdapter.STRING.decode(reader))
            6 -> detected_by = ProtoAdapter.STRING.decode(reader)
            7 -> player_mode = ProtoAdapter.STRING.decode(reader)
            8 -> preferred_audio_language = ProtoAdapter.STRING.decode(reader)
            9 -> preferred_subtitle_language = ProtoAdapter.STRING.decode(reader)
            10 -> default_video_quality = ProtoAdapter.STRING.decode(reader)
            11 -> max_bitrate_cap_mbps = ProtoAdapter.DOUBLE.decode(reader)
            12 -> visual_metadata = VisualMetadata.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PlayPayload(
          url = url,
          title = title,
          headers = headers,
          content_type = content_type,
          subtitles = subtitles,
          detected_by = detected_by,
          player_mode = player_mode,
          preferred_audio_language = preferred_audio_language,
          preferred_subtitle_language = preferred_subtitle_language,
          default_video_quality = default_video_quality,
          max_bitrate_cap_mbps = max_bitrate_cap_mbps,
          visual_metadata = visual_metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PlayPayload): PlayPayload = value.copy(
        visual_metadata = value.visual_metadata?.let(VisualMetadata.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
