// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.PlaylistStatusMessage in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class PlaylistStatusMessage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  items: List<PlaylistItemInfo> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currentIndex",
    schemaIndex = 2,
  )
  public val current_index: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "totalCount",
    schemaIndex = 3,
  )
  public val total_count: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PlaylistStatusMessage, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "playbridge.PlaylistItemInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val items: List<PlaylistItemInfo> = immutableCopyOf("items", items)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PlaylistStatusMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (items != other.items) return false
    if (current_index != other.current_index) return false
    if (total_count != other.total_count) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + items.hashCode()
      result = result * 37 + current_index.hashCode()
      result = result * 37 + total_count.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    if (items.isNotEmpty()) result += """items=$items"""
    result += """current_index=$current_index"""
    result += """total_count=$total_count"""
    return result.joinToString(prefix = "PlaylistStatusMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    items: List<PlaylistItemInfo> = this.items,
    current_index: Int = this.current_index,
    total_count: Int = this.total_count,
    unknownFields: ByteString = this.unknownFields,
  ): PlaylistStatusMessage = PlaylistStatusMessage(type, items, current_index, total_count,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PlaylistStatusMessage> = object :
        ProtoAdapter<PlaylistStatusMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      PlaylistStatusMessage::class, 
      "type.googleapis.com/playbridge.PlaylistStatusMessage", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: PlaylistStatusMessage): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        size += PlaylistItemInfo.ADAPTER.asRepeated().encodedSizeWithTag(2, value.items)
        if (value.current_index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.current_index)
        }
        if (value.total_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.total_count)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PlaylistStatusMessage) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        PlaylistItemInfo.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.items)
        if (value.current_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.current_index)
        }
        if (value.total_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.total_count)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PlaylistStatusMessage) {
        writer.writeBytes(value.unknownFields)
        if (value.total_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.total_count)
        }
        if (value.current_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.current_index)
        }
        PlaylistItemInfo.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.items)
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): PlaylistStatusMessage {
        var type: String = ""
        val items = mutableListOf<PlaylistItemInfo>()
        var current_index: Int = 0
        var total_count: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> items.add(PlaylistItemInfo.ADAPTER.decode(reader))
            3 -> current_index = ProtoAdapter.INT32.decode(reader)
            4 -> total_count = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PlaylistStatusMessage(
          type = type,
          items = items,
          current_index = current_index,
          total_count = total_count,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PlaylistStatusMessage): PlaylistStatusMessage = value.copy(
        items = value.items.redactElements(PlaylistItemInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
