// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.PlaylistPayload in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class PlaylistPayload(
  items: List<PlayPayload> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "startIndex",
    schemaIndex = 1,
  )
  public val start_index: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "playbridge.VisualMetadata#ADAPTER",
    jsonName = "visualMetadata",
    schemaIndex = 2,
  )
  public val visual_metadata: VisualMetadata? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PlaylistPayload, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "playbridge.PlayPayload#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val items: List<PlayPayload> = immutableCopyOf("items", items)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PlaylistPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (items != other.items) return false
    if (start_index != other.start_index) return false
    if (visual_metadata != other.visual_metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + items.hashCode()
      result = result * 37 + start_index.hashCode()
      result = result * 37 + (visual_metadata?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (items.isNotEmpty()) result += """items=$items"""
    result += """start_index=$start_index"""
    if (visual_metadata != null) result += """visual_metadata=$visual_metadata"""
    return result.joinToString(prefix = "PlaylistPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(
    items: List<PlayPayload> = this.items,
    start_index: Int = this.start_index,
    visual_metadata: VisualMetadata? = this.visual_metadata,
    unknownFields: ByteString = this.unknownFields,
  ): PlaylistPayload = PlaylistPayload(items, start_index, visual_metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PlaylistPayload> = object : ProtoAdapter<PlaylistPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      PlaylistPayload::class, 
      "type.googleapis.com/playbridge.PlaylistPayload", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: PlaylistPayload): Int {
        var size = value.unknownFields.size
        size += PlayPayload.ADAPTER.asRepeated().encodedSizeWithTag(1, value.items)
        if (value.start_index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.start_index)
        }
        size += VisualMetadata.ADAPTER.encodedSizeWithTag(3, value.visual_metadata)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PlaylistPayload) {
        PlayPayload.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.items)
        if (value.start_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.start_index)
        }
        VisualMetadata.ADAPTER.encodeWithTag(writer, 3, value.visual_metadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PlaylistPayload) {
        writer.writeBytes(value.unknownFields)
        VisualMetadata.ADAPTER.encodeWithTag(writer, 3, value.visual_metadata)
        if (value.start_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.start_index)
        }
        PlayPayload.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.items)
      }

      override fun decode(reader: ProtoReader): PlaylistPayload {
        val items = mutableListOf<PlayPayload>()
        var start_index: Int = 0
        var visual_metadata: VisualMetadata? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> items.add(PlayPayload.ADAPTER.decode(reader))
            2 -> start_index = ProtoAdapter.INT32.decode(reader)
            3 -> visual_metadata = VisualMetadata.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PlaylistPayload(
          items = items,
          start_index = start_index,
          visual_metadata = visual_metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PlaylistPayload): PlaylistPayload = value.copy(
        items = value.items.redactElements(PlayPayload.ADAPTER),
        visual_metadata = value.visual_metadata?.let(VisualMetadata.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
