// Code generated by Wire protocol buffer compiler, do not edit.
// Source: playbridge.SeriesEpisodeRef in messages.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package playbridge

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ==================== Shared Metadata ====================
 */
public class SeriesEpisodeRef(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val season: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val episode: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val title: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SeriesEpisodeRef, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SeriesEpisodeRef) return false
    if (unknownFields != other.unknownFields) return false
    if (season != other.season) return false
    if (episode != other.episode) return false
    if (title != other.title) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + season.hashCode()
      result = result * 37 + episode.hashCode()
      result = result * 37 + (title?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """season=$season"""
    result += """episode=$episode"""
    if (title != null) result += """title=${sanitize(title)}"""
    return result.joinToString(prefix = "SeriesEpisodeRef{", separator = ", ", postfix = "}")
  }

  public fun copy(
    season: Int = this.season,
    episode: Int = this.episode,
    title: String? = this.title,
    unknownFields: ByteString = this.unknownFields,
  ): SeriesEpisodeRef = SeriesEpisodeRef(season, episode, title, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SeriesEpisodeRef> = object : ProtoAdapter<SeriesEpisodeRef>(
      FieldEncoding.LENGTH_DELIMITED, 
      SeriesEpisodeRef::class, 
      "type.googleapis.com/playbridge.SeriesEpisodeRef", 
      PROTO_3, 
      null, 
      "messages.proto"
    ) {
      override fun encodedSize(`value`: SeriesEpisodeRef): Int {
        var size = value.unknownFields.size
        if (value.season != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.season)
        }
        if (value.episode != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.episode)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.title)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SeriesEpisodeRef) {
        if (value.season != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.season)
        }
        if (value.episode != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.episode)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.title)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SeriesEpisodeRef) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.title)
        if (value.episode != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.episode)
        }
        if (value.season != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.season)
        }
      }

      override fun decode(reader: ProtoReader): SeriesEpisodeRef {
        var season: Int = 0
        var episode: Int = 0
        var title: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> season = ProtoAdapter.INT32.decode(reader)
            2 -> episode = ProtoAdapter.INT32.decode(reader)
            3 -> title = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SeriesEpisodeRef(
          season = season,
          episode = episode,
          title = title,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SeriesEpisodeRef): SeriesEpisodeRef = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
